Qa/combine prerelease regression
sepulsa/.github pull request #4
Opened 2021-04-15 06:16 UTC by SatrioAjieWijaya

penambahan file untuk handle prerelease+regression dan regression yang di trigger secara manual

2021-04-16 01:14 UTC, el7cosmos requested changes
yang `manual-reg.yml` gabungin ke `regression.yml` aja, terus `prerelease-reg.yml` gabung ke `prerelease.yml`

2021-04-19 02:29 UTC, el7cosmos requested changes

2021-04-19 02:29 UTC, el7cosmos commented on workflow-templates/prerelease.yml
> -    branches: [ $default-branch ]
Keep this 2 lines

2021-04-19 02:29 UTC, el7cosmos commented on workflow-templates/regression.yml
> +      # - name: Set Report Portal Parameters
Remove this commented out lines

2021-04-19 02:29 UTC, el7cosmos commented on workflow-templates/regression.yml
> +        # env:
Remove this commented out lines

2021-04-19 02:29 UTC, el7cosmos commented on workflow-templates/prerelease.yml
> +      - run: echo head_ref is ${{ github.head_ref }} | cut -d'/' -f 2
Remove this

2021-04-19 02:29 UTC, el7cosmos commented on workflow-templates/prerelease.yml
> -      - run: echo 'Deployed'
Keep this for now, let infra hooks into this

2021-04-19 07:50 UTC, el7cosmos approved these changes

2021-04-19 07:51 UTC, el7cosmos commented
LGTM
@billyjulius bisa bantu review?

2021-04-19 08:51 UTC, billyjulius approved these changes

2021-04-19 09:08 UTC, merged